#cloud-config
install:
    device: /dev/sda
    auto: true
    poweroff: true
hostname: minis-{{ trunc 4 .MachineID }}
users:
    - name: kairos
      ssh_authorized_keys:
        - github:HasseJohansen
k3s:
    enabled: true
    args:
        - --disable=traefik,servicelb
kubevip:
    eip: 192.168.8.8
p2p:
    # Disabling DHT makes co-ordination to discover nodes only in the local network
    #Enabled by default
    disable_dht: true
    vpn:
        # defaults to true
        create: false
        # defaults to true
        use: false
    # network_token is the shared secret used by the nodes to co-ordinate with p2p.
    # Setting a network token implies auto.enable = true.
    # To disable, just set auto.enable = false
    network_token: ENC[AES256_GCM,data:g15UoM88enBoAeFkDPwNZWeaAJ6AkW9eWh3OjzRZcDuWiuU6NvGEeBOs0hTbwGnlG6YN01I+XrP9xGBZtpEAvFg2YRpWqvzK/MTPbyHxNVUKJKW4pNQjl82No5mEDZfhV7EqGRWosZlS1RscFyEbm3jM+V1F+vaKtiyDCA6zB9LBkftSHLrYF7WYEXC79B2GP/8wdHoewt+phhoJrGPH1JYIkdCUjb1xnajkSzT/nf3JuetJNcNDAkQN+iJ7yoZBdiOUjP45qrLH740UOAwNqsTyxPaNnJ6vak781XYwLUaG52A7lT2I6XasEe4ga5cS6p2+W8Fq/B2RE8q8b07tPn4pSUWfHzJj1oGEtxfWDnO5xeN78Ci1LmMYb5ewCxQbRvKcF4I5scTVEs1KEfm6LyQXMYFTjjFfntiMR2pqOE2+oes8V5etk3DOdMdgdDb2ANP7u57U5RIBKDypxnPEsH24J3KMTOQvpQJZoaOZMkKlVrlxt2bK5vPLlEtsl4hXQNFhDvy10Rz9p39rV8KMSg3YCOWOinU/TX2WYMAoNbm49c0mx2v2klrLm4ryOBx2NuNeV9YLFD2BoUuQeZjEQULAk3XYCfXxaqIx1svZuyzWh6N5q7zRLbVUCz32/LBpayKk/nSzzwntVeR3nrjFdIEg+u959q3RPsT10Q==,iv:TN4PnrnsV/U1nmRPjc+4e0cUhX3wyLQk5Z4HPJ1CmH8=,tag:Mc5hqCMlUNHuu/452kAvyQ==,type:str]
    # Automatic cluster deployment configuration
    auto:
        # Enables Automatic node configuration (self-coordination)
        # for role assignment
        enable: true
        # HA enables automatic HA roles assignment.
        # A master cluster init is always required,
        # Any additional master_node is configured as part of the
        # HA control plane.
        # If auto is disabled, HA has no effect.
        ha:
            # Enables HA control-plane
            enable: true
            # Number of HA additional master nodes.
            # A master node is always required for creating the cluster and is implied.
            # The setting below adds 2 additional master nodes, for a total of 3.
            master_nodes: 1
bundles:
    - targets:
        - run://hassejohansen/flux:latest
flux:
    env:
        GITHUB_TOKEN: ENC[AES256_GCM,data:wb2Vk8/XzpezmF4NdMJqrdruop8Np8AqNJxsRwJvQ76bDbFJibyRUg==,iv:9S34+0vv1LeCEWjbISc64VSWDtrXunJBiUuI17QMjms=,tag:PfB5FpVIgYHVfqkimELtMA==,type:str]
    github:
        owner: HasseJohansen
        repository: fleet-infra
        path: clusters/minis
        components-extra: image-reflector-controller,image-automation-controller
        network-policy: "false"
stages:
    after-install-chroot:
        - files:
            - path: /etc/systemd/network/10-dhcp.network
              owner: 0
              group: 0
              permissions: 420
              content: |
                [Match]
                Name=enp47s0
                [Link]
                Unmanaged=yes
          commands:
            - rm -f /var/lib/dbus/machine-id
            - rm -f /etc/machine-id
            - dbus-uuidgen --ensure
            - systemd-machine-id-setup
            - sed -i '/^config_url:.*$/d' /oem/90_custom.yaml
        - name: Create data dir
          commands:
            - mkdir -p /data
        - name: Format /dev/nvme0n1
          commands:
            - mkfs.ext4 -F /dev/nvme0n1
        - name: Setup mdns resolving
          commands:
            - echo "MulticastDNS=yes" >> /etc/systemd/resolved.conf
            - sed -i -e 's/\(DHCP=yes\)/\1\nMulticastDNS=yes/g' /etc/systemd/network/20-dhcp.network
    # Creates the data dir after reset inside the final system chroot, just in case it's not there
    after-reset-chroot:
        - !!merge <<:
            name: Create data dir
            commands:
                - mkdir -p /data
    # Creates the data dir after upgrade inside the final system chroot, just in case it's not there
    after-upgrade-chroot:
        - !!merge <<:
            name: Create data dir
            commands:
                - mkdir -p /data
    initramfs:
        # Mounts the disk under the /data dir during initramfs on each boot, with RW. Extra options can be added to the mount here
        - name: Mount /dev/nvme0n1 under /data
          commands:
            - mount -o rw /dev/nvme0n1 /data
    boot:
        - name: Add flux-system namespace manifest
          files:
            - path: /var/lib/rancher/k3s/server/manifests/flux-system.yaml
              content: |
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: flux-system
        - name: Download SOPS secret
          files:
            - path: /var/lib/rancher/k3s/server/manifests/sops-secret.yaml
              content: |
                apiVersion: v1
                data:
                  age.agekey: <AGE key>
                kind: Secret
                type: Opaque
                metadata:
                  name: sops-age
                  namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRGUyZmpWdVFhSVRnOC9F
            MkNaYzVoclYvclFrWGFIUFdDcEhvVHdrYXlzCnlwamdOVlk5WnZ0LzNDVTRGNnlF
            dzF0aXJzZGxqeVp0VXQxUUFERFRuczgKLS0tIHBURWhvenNGMjhkTU9UdmplaXdV
            RXFKZnRac3ZkZHRNRGlmVTlWbjlEWEEK87cnG+szRt7PAuNMkVyhpAdpOVUwwNpU
            /b+8/jbeGoiO6EF+WVJ9bVeLrevI2E3p6JOVzQJ15nTFTwR/zS3lvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T12:53:46Z"
    mac: ENC[AES256_GCM,data:hkUkX1T0U4Pd3Jbx9jdKgiJulDtD9jhSLNo0RefpFGxhqRLs+z5bRuL5qjSyWjsLj5Dk7rSNTQ7rZsxk0ZTfAYlty37v2ulbAU4WkPxr/On5kVIDYGdgWfJChxGSuLKm0NOeF3cd5sWL5L4NKJP6dwWqXHuYIa37yYh6i9RAlN0=,iv:dJF+gjpZNCHUHEqEdRkRzwhh2dW2eSOPOKQq+cOywMs=,tag:sQc/2AH+KbOlp4e9gWMPww==,type:str]
    pgp: []
    encrypted_regex: ^(GITHUB_TOKEN|network_token)$
    version: 3.8.1
