#cloud-config
install:
    device: /dev/sda
    auto: true
    poweroff: true
hostname: minis-{{ trunc 4 .MachineID }}
users:
    - name: kairos
      ssh_authorized_keys:
        - github:HasseJohansen
k3s:
    enabled: true
    args:
        - --disable=traefik,servicelb
kubevip:
    eip: 192.168.8.8
p2p:
    # Disabling DHT makes co-ordination to discover nodes only in the local network
    #Enabled by default
    disable_dht: true
    vpn:
        # defaults to true
        create: false
        # defaults to true
        use: false
    # network_token is the shared secret used by the nodes to co-ordinate with p2p.
    # Setting a network token implies auto.enable = true.
    # To disable, just set auto.enable = false
    network_token: ENC[AES256_GCM,data:I/fS/ZOdMFBzVq92G/i19MF8icbzo2qImRSFbc6NULj4vO0LBF19yL1w1JJv/W5O6RiYmbsTasTrENMy0VpdIZEwpMYb7Uq8q8/OTNuCOb/lVPezfK9mk5a4Qln22LpH5oEOdPe4gWFVxNO3WiwSpk0T5quuq00LElVm4Syg2mNEsY+0zBAyPvlH3yL/DcxLIjCDh3wW9fooVrYYBmGdVSdkY13HjtM63ZdKwmuDjQklQSolVPzgIfBoxjmeRKJvdRE51DM3K4IJrX62tiYU7+ohGRhxG+bDy22jPRs9WYXVsT3p0m0e1NKwmCF7qzWf4YgjwuusyP49AaSd2/4Umjhcb1Y6g+0VAhXzsSk3hW+sTYQvONQ3H4ylVC9Hg1xHYb0Ds1CejzC0Ls2WqcjqD+mXX1KLE/dQforvy8ZLZIzxflCpgYIGzXBEG6K9I3pi8Gs+PqCAI2z13JPZHl4Eulp/lrK/TAmnClQqwaIdq3uL2UVmRkU6pIKiSsezktezZlgyT7ZQNYRsskAVbBIpeI9pem7lnZNO/gDd+uimxxt3yt+fbWoGEeHGOVOyxaIxMe9/ly1Nmq/9w1n9GSHkGARsessQ7ZnbRRswPgxc/VFdRnSY2jwhgHHAT7Aq9GIohjLDvEpog3kno8+S4h5jn2hLp451SXKJjnZvfQ==,iv:rZw4/sIvXnXu4Y++DFmNOhqYbEWtelMEoghTRXMb5VA=,tag:Q0OLAoWfz2hY2VPveYV6uw==,type:str]
    # Automatic cluster deployment configuration
    auto:
        # Enables Automatic node configuration (self-coordination)
        # for role assignment
        enable: true
        # HA enables automatic HA roles assignment.
        # A master cluster init is always required,
        # Any additional master_node is configured as part of the
        # HA control plane.
        # If auto is disabled, HA has no effect.
        ha:
            # Enables HA control-plane
            enable: true
            # Number of HA additional master nodes.
            # A master node is always required for creating the cluster and is implied.
            # The setting below adds 2 additional master nodes, for a total of 3.
            master_nodes: 1
bundles:
    - targets:
        - run://hassejohansen/flux:latest
flux:
    env:
        GITHUB_TOKEN: ENC[AES256_GCM,data:r3AXr6nR7QsgPr6lAeGc3DS3GAicGKjcz2Alg1vtqk7d7E6O7s/uSw==,iv:diV1Vl+uUDHxAbsb51kvn5p+sDAK4cxqOVDzr9fuh6U=,tag:rxY4y9VduBCLy8H2mCm53Q==,type:str]
    github:
        owner: HasseJohansen
        repository: fleet-infra
        path: clusters/minis
        components-extra: image-reflector-controller,image-automation-controller
        network-policy: "false"
stages:
    after-install-chroot:
        - files:
            - path: /etc/systemd/network/10-dhcp.network
              owner: 0
              group: 0
              permissions: 420
              content: |
                [Match]
                Name=enp47s0
                [Link]
                Unmanaged=yes
          commands:
            - rm -f /var/lib/dbus/machine-id
            - rm -f /etc/machine-id
            - dbus-uuidgen --ensure
            - systemd-machine-id-setup
            - sed -i '/^config_url:.*$/d' /oem/90_custom.yaml
        - name: Create data dir
          commands:
            - mkdir -p /data
        - name: Format /dev/nvme0n1
          commands:
            - mkfs.ext4 -F /dev/nvme0n1
        - name: Setup mdns resolving
          commands:
            - echo "MulticastDNS=yes" >> /etc/systemd/resolved.conf
    # Creates the data dir after reset inside the final system chroot, just in case it's not there
    after-reset-chroot:
        - !!merge <<:
            name: Create data dir
            commands:
                - mkdir -p /data
    # Creates the data dir after upgrade inside the final system chroot, just in case it's not there
    after-upgrade-chroot:
        - !!merge <<:
            name: Create data dir
            commands:
                - mkdir -p /data
    initramfs:
        # Mounts the disk under the /data dir during initramfs on each boot, with RW. Extra options can be added to the mount here
        - name: Mount /dev/nvme0n1 under /data
          commands:
            - mount -o rw /dev/nvme0n1 /data
    boot:
        - name: Add flux-system namespace manifest
          files:
            - path: /var/lib/rancher/k3s/server/manifests/flux-system.yaml
              content: |
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: flux-system
        - name: Download SOPS secret
          files:
            - path: /var/lib/rancher/k3s/server/manifests/sops-secret.yaml
              content: |
                apiVersion: v1
                data:
                  age.agekey: <AGE key>
                kind: Secret
                type: Opaque
                metadata:
                  name: sops-age
                  namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV2FIWFlsbXRjbGorS2xj
            MVVOWXFkdUZrTXhiVFBrc3BhcS93STV0R2gwCkJMazE2ZDl0K0tjZ1ZtQ2FWYUYr
            eHh3S3JDR3d4NFdQRzQzUys5WUVyOUkKLS0tIG00WUo5MmV5N2YvZzE4QXczUFMr
            RnpYSHdWMUhMQi9BMXh2T2FsN0tKaW8KkYgkf7LXjIzmDZjpNUhTa7StAXZCRsrI
            XJDY+mOu53qlN7pufjOKeYs5CNKWAAHLJ/4+rEQQMjBAHZzX/qKZCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T12:34:29Z"
    mac: ENC[AES256_GCM,data:GOUhMJo2gJrryy4/2AsXzn66fOR1kGsc9nvZU9rxb90x06dR5dZLV0TgtS19f9Ljd54vAxMxwG2jCD5mue7U0P4axMyhj70DGtnnZ9BhjrU769q15FdeHAIuHcx3or+oz4Pbzd2yMIORY+L0fNT5Iml6hxfYSLZRD6unMZo3USs=,iv:U9rM8IEhTu9gM18prIaQQcqK/ZGFGkzpISggQjxwjW0=,tag:PaiNmmpVZUzu0r0un0+G/g==,type:str]
    pgp: []
    encrypted_regex: ^(GITHUB_TOKEN|network_token)$
    version: 3.8.1
