#cloud-config
install:
    device: /dev/sda
    auto: true
    poweroff: true
    grub_options:
        extra_cmdline: selinux=0
hostname: minis-{{ trunc 4 .MachineID }}
users:
    - name: kairos
      groups:
        - admin
      ssh_authorized_keys:
        - github:HasseJohansen
k3s:
    enabled: true
    args:
        - --disable=traefik,servicelb
        - --prefer-bundled-bin
kubevip:
    eip: 192.168.8.8
p2p:
    # Disabling DHT makes co-ordination to discover nodes only in the local network
    #Enabled by default
    disable_dht: true
    vpn:
        # defaults to true
        create: false
        # defaults to true
        use: false
    # network_token is the shared secret used by the nodes to co-ordinate with p2p.
    # Setting a network token implies auto.enable = true.
    # To disable, just set auto.enable = false
    network_token: ENC[AES256_GCM,data:21FKbIrprwq8myRTQtKEMLZMOQkasWBBilVOKMgZLnLrfZwSa9DuvvMykSnDvgEU4jrNPGh9pjzI2zJetkDX9ueHhG49pcTCJv190x7fzIljtElcm70C9vPVwUNpHo+WAeFyO/hk3lq4z7l+YeAzRMJfD9ob1cyN1qjn0dGPZB2RESSaqdc/symLnJ1Sgmz2AX+Ih+oMAQMPxa7OnPdCZAM6JTYYc2eyheGtgsAMvNO7M4/XEiqE84jduEPBwpXAzRTngcS1mTFbe0MKu/xuY6Sq25bxKOdC7JdoZsli5YjO0+yrqtzz+3odHFR4XVEocDjtqf76LF8EMKuxjtbm3VzUiWrByHmmPqoCq7b/hkwqNCRMzNft9Svblron1DSCQrDuu6Pe8EAzpjO/YWpuBfIZ1hoRIZVDZImVPotXO7VhT3ESDN9tDLNTlwhDjlMAOvSoYXcXjYQO1EOHKLTon5Y0Z8Q3pfyMF/iduTPuFsXpsMhUs23xNeq0os0hLSIG5K7sTnEOeR5MPYtC4fjGvO7n4TZoOU/xrMxf9HGNn0VTERt0c4p8McLx+r0witUVyZWdDUrLzFCAta+XVix1VBoM8BxfnArEPVly3BB12J/b8BMIdXrortCZdyKgQla1IYQyAlV1azp9ZpQCo/AF6gbKfOmBOoBLZlsVMA==,iv:9keQCBoHJmAcHFTgB1vGl4OBokQfaj5HbN8GxHlYKEw=,tag:42QZWNkdd54gU8GdAJlxXg==,type:str]
    # Automatic cluster deployment configuration
    auto:
        # Enables Automatic node configuration (self-coordination)
        # for role assignment
        enable: true
        # HA enables automatic HA roles assignment.
        # A master cluster init is always required,
        # Any additional master_node is configured as part of the
        # HA control plane.
        # If auto is disabled, HA has no effect.
        ha:
            # Enables HA control-plane
            enable: true
            # Number of HA additional master nodes.
            # A master node is always required for creating the cluster and is implied.
            # The setting below adds 2 additional master nodes, for a total of 3.
            master_nodes: 2
bundles:
    - targets:
        - run://hassejohansen/flux:2.4.0
flux:
    env:
        GITHUB_TOKEN: ENC[AES256_GCM,data:c2/B/5vJqf+lsj/f7hqCddyEfiY/KrRqpep8lyHscgCpys97T9wi9w==,iv:PPaeeyNZfICbLVD05LxgRmYGiQxUbQUmdg66S3IomTY=,tag:TZbsCoIoi8wlNewSBLzPkw==,type:str]
    github:
        owner: HasseJohansen
        repository: fleet-infra
        path: clusters/minis
        components-extra: image-reflector-controller,image-automation-controller
        network-policy: "false"
stages:
    after-install-chroot:
        - files:
            - path: /etc/systemd/network/10-dhcp.network
              owner: 0
              group: 0
              permissions: 420
              content: |
                [Match]
                Name=enp47s0
                [Link]
                Unmanaged=yes
          commands:
            - rm -f /var/lib/dbus/machine-id
            - rm -f /etc/machine-id
            - dbus-uuidgen --ensure
            - systemd-machine-id-setup
            - sed -i '/^config_url:.*$/d' /oem/90_custom.yaml
        - name: Create data dir
          commands:
            - mkdir -p /data
        - name: Format /dev/nvme0n1
          commands:
            - mkfs.ext4 -F /dev/nvme0n1
            #        - name: Setup mdns resolving
            #commands:
            #- echo "MulticastDNS=yes" >> /etc/systemd/resolved.conf
            #- sed -i -e 's/\(DHCP=yes\)/\1\nMulticastDNS=yes/g' /etc/systemd/network/20-dhcp.network
    # Creates the data dir after reset inside the final system chroot, just in case it's not there
    after-reset-chroot:
        - !!merge <<:
            name: Create data dir
            commands:
                - mkdir -p /data
    # Creates the data dir after upgrade inside the final system chroot, just in case it's not there
    after-upgrade-chroot:
        - !!merge <<:
            name: Create data dir
            commands:
                - mkdir -p /data
    initramfs:
        # Mounts the disk under the /data dir during initramfs on each boot, with RW. Extra options can be added to the mount here
        - name: Mount /dev/nvme0n1 under /data
          commands:
            - mount -o rw /dev/nvme0n1 /data
    boot:
        - name: Add flux-system namespace manifest
          files:
            - path: /var/lib/rancher/k3s/server/manifests/flux-system.yaml
              content: |
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: flux-system
        - name: Download SOPS secret
          files:
            - path: /var/lib/rancher/k3s/server/manifests/sops-secret.yaml
              content: |
                apiVersion: v1
                data:
                  age.agekey: <placeholder>
                kind: Secret
                type: Opaque
                metadata:
                  name: sops-age
                  namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MC9ZVVN6bERWbm1RV1VM
            MS9vZSs3WHExUlJvOXhEV0RhdTJvMnRzNmxZCjlobnAzK1R0R0lRR1B0YTJnaGpP
            RzVSYWxmNW8yNENHUzdWeU9DcDQ2UEEKLS0tIC9HWnEyRS9hV3RSV2Z3OGkvdzZ1
            TFBUdytZMHVmZ1lTZURiZGUyKy92S3MKJ3qS+FWUdNXlbTiXLXhCEdgbihkjgOv2
            u18h4mT2drfL7pyBlnqanWXgu1JvbACW3cdFPKsMtAsnMcDIM68wEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-04T09:41:13Z"
    mac: ENC[AES256_GCM,data:fy3mziHq9bNq+S5okvbS5qgljBoveE4nNBlPsbeMTQk1Mk85gpmoBKEyaN6WTMWGEVp20dIO83LiEtga+VOfR3xUxpJSKSfeJOTY7KvR2jEXAeCypvZxcY2gx/OHFhkZyd3wErHTFuPaFunFY6rw+nX1aH5zHnNX6OYDi/JByLI=,iv:npEYqSBRjrtGgbe6m0tvjHL1TgrvTD4JuKIh3rbQXwc=,tag:Tu40Fs4WPi3dpS+irgQSBA==,type:str]
    pgp: []
    encrypted_regex: ^(GITHUB_TOKEN|network_token)$
    version: 3.9.1
